USE GESTIONCLIENTE;

/*PRUEBA DE PROCEDURE DE INGRESO DE CLIENTE*/
START TRANSACTION;
CALL SP_INS_CLIENTE('PRUEBA', 'PROCEDURE', '50936700', 'A@GMAIL.COM', 'CONECTADO', ' ', 'CASA');
SELECT * FROM CLIENTE;
ROLLBACK;

/*PRUEBA DE PROCEDURE DE INGRESO DE CONTRATO*/
START TRANSACTION;
CALL SP_INS_CONTRATO(20, 20, 8, 20, CAST('2025-11-20' AS DATE), CAST('2026-11-20' AS DATE), 'CONECTADO');
SELECT * FROM CONTRATO;
SELECT * FROM CONTRATOPRM;
ROLLBACK;

/*PRUEBA DE PROCEDURE DE INGRESO DE FACTURA*/
START TRANSACTION;
CALL SP_INS_FACTURA(4, 0, CURDATE(), NULL);
SELECT * FROM FACTURA;
SELECT * FROM FACTURALINEA;
ROLLBACK;

/*PRUEBA DE TRIGGER DE UPDATE DE ULTIMA LINEA EN FACTURA*/
START TRANSACTION;
INSERT INTO FACTURALINEA (ID_FACTURA,ID_FACTURALIN,ID_CONTRATO,FAC_LIN_IMP) VALUES (1,4,4,200);
SELECT * FROM FACTURA WHERE ID_FACTURA = 1;
SELECT * FROM FACTURALINEA WHERE ID_FACTURA = 1;
ROLLBACK;

/*PRUEBA DE TRIGGER AUDITORIA DE POLTIICA*/
START TRANSACTION;
UPDATE POLITICA SET POL_PRECIO = 750 WHERE ID_POLITICA = 1;
SELECT * FROM LOG_POLITICA WHERE ID_POLITICA = 1;
ROLLBACK;

SELECT * FROM PROMOCION;

SELECT * FROM LOG_PROMOCION WHERE ID_PROMOCION = 1;

/*PRUEBA DE TRIGGER AUDITORIA DE PROMOCION*/
START TRANSACTION;
UPDATE PROMOCION SET PRM_DTO = 50 WHERE ID_PROMOCION = 1;
SELECT * FROM LOG_PROMOCION WHERE ID_PROMOCION = 1;
ROLLBACK;

/*PRUEBA DE TRIGGER AUDITORIA DE PROMOCION*/
START TRANSACTION;
UPDATE PROMOCION SET PRM_CNT_MESES = 5 WHERE ID_PROMOCION = 1;
SELECT * FROM LOG_PROMOCION WHERE ID_PROMOCION = 1;
ROLLBACK;

/*PRUEBA DE TRIGGER AUDITORIA DE PROMOCION*/
START TRANSACTION;
UPDATE PROMOCION SET PRM_DTO = 50, PRM_CNT_MESES = 5 WHERE ID_PROMOCION = 1;
SELECT * FROM LOG_PROMOCION WHERE ID_PROMOCION = 1;
ROLLBACK;