CREATE SCHEMA GESTIONCLIENTE;
USE GESTIONCLIENTE;

CREATE TABLE EMPRESA (
  ID_EMPRESA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  EMP_NOMBRE VARCHAR(100) NOT NULL,
  RUT VARCHAR(30) NOT NULL
);

CREATE TABLE NUMERADOR (
	ID_EMPRESA INT NOT NULL,
  ENTIDAD VARCHAR(50) NOT NULL,
  ULTIMO_NUM INT NOT NULL,
  PRIMARY KEY (ID_EMPRESA,ENTIDAD),
  CONSTRAINT FK_NUM_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA)
);

CREATE TABLE ESTADO (
  ID_ESTADO INT NOT NULL PRIMARY KEY,
  ENTIDAD VARCHAR(30) NOT NULL,
  DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCTO (
  ID_EMPRESA INT NOT NULL,
  ID_PRODUCTO INT NOT NULL,
  PRD_NOMBRE VARCHAR(100) NOT NULL,
  ID_ESTADO INT NOT NULL,
  PRIMARY KEY (ID_EMPRESA,ID_PRODUCTO),
  CONSTRAINT FK_PRODUCTO_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
  CONSTRAINT FK_PRODUCTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

CREATE INDEX IX_PRODUCTO_ESTADO ON PRODUCTO (ID_EMPRESA,ID_ESTADO);

CREATE TABLE POLITICA (
  ID_EMPRESA INT NOT NULL,
  ID_POLITICA INT NOT NULL,
  POL_NOMBRE VARCHAR(100) NOT NULL,
  POL_PRECIO DECIMAL(10,2) NOT NULL,
  ID_ESTADO INT NOT NULL,
  PRIMARY KEY (ID_EMPRESA,ID_POLITICA),
  CONSTRAINT FK_POLITICA_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
  CONSTRAINT FK_POLITICA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

CREATE INDEX IX_POLITICA_ESTADO ON POLITICA (ID_EMPRESA,ID_ESTADO);

CREATE TABLE PRODUCTOPOL (
  ID_EMPRESA INT NOT NULL,
  ID_PRODUCTO INT NOT NULL,
  ID_POLITICA INT NOT NULL,
  PRIMARY KEY (ID_EMPRESA,ID_PRODUCTO,ID_POLITICA),
  CONSTRAINT FK_PRODUCTOPOL_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
  CONSTRAINT FK_PRODUCTOPOL_PRODUCTO FOREIGN KEY (ID_EMPRESA,ID_PRODUCTO) REFERENCES PRODUCTO (ID_EMPRESA,ID_PRODUCTO),
  CONSTRAINT FK_PRODUCTOPOL_POLITICA FOREIGN KEY (ID_EMPRESA,ID_POLITICA) REFERENCES POLITICA (ID_EMPRESA,ID_POLITICA)
);

CREATE TABLE CLIENTE (
  ID_EMPRESA INT NOT NULL,
  ID_CLIENTE INT NOT NULL,
  CLI_NOMBRE VARCHAR(100) NOT NULL,
  CLI_APELLIDO VARCHAR(100) NOT NULL,
  DNI VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(100),
  ID_ESTADO INT NOT NULL,
  CLI_TELEFONO VARCHAR(20),
  DIRECCION VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_EMPRESA,ID_CLIENTE),
  CONSTRAINT FK_CLIENTE_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
  CONSTRAINT FK_CLIENTE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

CREATE INDEX IX_CLIENTE_DNI ON CLIENTE (DNI);
CREATE INDEX IX_CLIENTE_EMAIL ON CLIENTE (EMAIL);
CREATE INDEX IX_CLIENTE_ESTADO ON CLIENTE (ID_EMPRESA,ID_ESTADO);

CREATE TABLE CONTRATO (
  ID_EMPRESA INT NOT NULL,
  ID_CONTRATO INT NOT NULL,
  ID_PRODUCTO INT NOT NULL,
  ID_POLITICA INT NOT NULL,
  ID_CLIENTE INT NOT NULL,
  ID_ESTADO INT NOT NULL,
  FCH_CONTRATO DATE NOT NULL,
  FCH_VIGENCIA DATE,
  FCH_FIN DATE,
  PRIMARY KEY (ID_EMPRESA,ID_CONTRATO),
  CONSTRAINT FK_CONTRATO_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
  CONSTRAINT FK_CONTRATO_PRODUCTO FOREIGN KEY (ID_EMPRESA,ID_PRODUCTO) REFERENCES PRODUCTO (ID_EMPRESA,ID_PRODUCTO),
  CONSTRAINT FK_CONTRATO_POLITICA FOREIGN KEY (ID_EMPRESA,ID_POLITICA) REFERENCES POLITICA (ID_EMPRESA,ID_POLITICA),
  CONSTRAINT FK_CONTRATO_CLIENTE FOREIGN KEY (ID_EMPRESA,ID_CLIENTE) REFERENCES CLIENTE (ID_EMPRESA,ID_CLIENTE),
  CONSTRAINT FK_CONTRATO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

CREATE INDEX IX_CONTRATO_CLIENTE ON CONTRATO (ID_EMPRESA,ID_CLIENTE);
CREATE INDEX IX_CONTRATO_ESTADO ON CONTRATO (ID_EMPRESA,ID_ESTADO);
CREATE INDEX IX_CONTRATO_PRODUCTO ON CONTRATO (ID_EMPRESA,ID_PRODUCTO);
CREATE INDEX IX_CONTRATO_VIGENCIA ON CONTRATO (ID_EMPRESA,FCH_VIGENCIA,FCH_FIN);

CREATE TABLE FACTURA (
  ID_EMPRESA INT NOT NULL,
  ID_FACTURA INT NOT NULL,
  ID_CLIENTE INT NOT NULL,
  ID_ESTADO INT NOT NULL,
  FAC_FCH DATE NOT NULL,
  FAC_TOTAL DECIMAL(10,2) NOT NULL,
  FAC_FCH_PAGO DATE,
  PRIMARY KEY (ID_EMPRESA,ID_FACTURA),
  CONSTRAINT FK_FACTURA_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
  CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (ID_EMPRESA,ID_CLIENTE) REFERENCES CLIENTE (ID_EMPRESA,ID_CLIENTE),
  CONSTRAINT FK_FACTURA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

CREATE INDEX IX_FACTURA_CLIENTE ON FACTURA (ID_EMPRESA,ID_CLIENTE);
CREATE INDEX IX_FACTURA_ESTADO ON FACTURA (ID_EMPRESA,ID_ESTADO);
CREATE INDEX IX_FACTURA_FECHA ON FACTURA (ID_EMPRESA,FAC_FCH);
CREATE INDEX IX_FACTURA_PAGO ON FACTURA (ID_EMPRESA, FAC_FCH_PAGO);

CREATE TABLE FACTURALINEA (
  ID_EMPRESA INT NOT NULL,
  ID_FACTURA INT NOT NULL,
  ID_FACTURALIN INT NOT NULL,
  ID_CONTRATO INT NOT NULL,
  FAC_LIN_IMP DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ID_EMPRESA,ID_FACTURA,ID_FACTURALIN),
  CONSTRAINT FK_FACTURALIN_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
  CONSTRAINT FK_FACTURALIN_FACTURA FOREIGN KEY (ID_EMPRESA,ID_FACTURA) REFERENCES FACTURA (ID_EMPRESA,ID_FACTURA),
  CONSTRAINT FK_FACTURALIN_CONTRATO FOREIGN KEY (ID_EMPRESA,ID_CONTRATO) REFERENCES CONTRATO (ID_EMPRESA,ID_CONTRATO)
);

CREATE TABLE ORDENTIPO (
  ID_ORDENTPO VARCHAR(1) NOT NULL PRIMARY KEY,
  DESCRIPCION VARCHAR(30) NOT NULL
);

CREATE TABLE ORDENSERVICIO (
  ID_EMPRESA INT NOT NULL,
  ID_ORDEN INT NOT NULL,
  ID_CONTRATO INT NOT NULL,
  ID_ORDENTPO VARCHAR(1) NOT NULL,
  ORD_FCH DATE NOT NULL,
  ORD_FCH_FIN DATE,
  ID_ESTADO INT NOT NULL,
  PRIMARY KEY (ID_EMPRESA,ID_ORDEN),
  CONSTRAINT FK_ORDENSRV_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
  CONSTRAINT FK_ORDENSRV_CONTRATO FOREIGN KEY (ID_EMPRESA,ID_CONTRATO) REFERENCES CONTRATO (ID_EMPRESA,ID_CONTRATO),
  CONSTRAINT FK_ORDENSRV_ORDENTPO FOREIGN KEY (ID_ORDENTPO) REFERENCES ORDENTIPO (ID_ORDENTPO),
  CONSTRAINT FK_ORDENSRV_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

CREATE INDEX IX_ORDENSRV_CONTRATO ON ORDENSERVICIO (ID_EMPRESA,ID_CONTRATO);
CREATE INDEX IX_ORDENSRV_ESTADO ON ORDENSERVICIO (ID_EMPRESA,ID_ESTADO);
CREATE INDEX IX_ORDENSRV_FECHA ON ORDENSERVICIO (ID_EMPRESA,ORD_FCH);